language: php
php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  # install composer and vendors
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

  # install Pear dependencies
  - pyrus install pear/PHP_CodeSniffer

  # install scrutinizer-ci
  wget https://scrutinizer-ci.com/ocular.phar

  - phpenv rehash

script:
  - phpcs --standard=psr2 src/
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - php vendor/bin/coveralls --env=test

  # scrutinizer-ci
  phpunit --coverage-clover=build/logs/coverage.clover
  php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover
